# Dependabot configuration for skeletor

version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    assignees:
      - "jml6m"
    open-pull-requests-limit: 1

updates:
  - package-ecosystem: "npm"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
