import {
  buildGitignore,
  buildKnipConfig,
  buildJscpdConfig,
  validateTemplateFeatures,
} from '../src/features.js';
import { getTemplatesWithManifests } from '../src/index.js';

process.env.SKELETOR_CLI_TEST = '1';

describe('features registry', () => {
  test('buildGitignore merges feature fragments', () => {
    const out = buildGitignore(['node', 'jest', 'jscpd']);
    expect(out).toContain('node_modules/');
    expect(out).toContain('coverage/');
    expect(out).toContain('.jscpd/');
    expect(out).toContain('Generated by skeletor from template features');
  });

  test('buildKnipConfig respects language', () => {
    const js = buildKnipConfig(['knip'], { language: 'javascript' });
    const ts = buildKnipConfig(['knip'], { language: 'typescript' });
    expect(js.entry[0]).toContain('.js');
    expect(ts.entry[0]).toContain('.ts');
  });

  test('buildJscpdConfig respects language', () => {
    const ts = buildJscpdConfig(['jscpd'], { language: 'typescript' });
    expect(ts.formatsExts.typescript).toEqual(['ts', 'tsx']);
  });

  test('all templates with features pass validation', () => {
    const templates = getTemplatesWithManifests();
    const errors = templates.flatMap((t) => validateTemplateFeatures(t));
    expect(errors).toEqual([]);
  });
});