import fs from 'fs';
import path from 'path';
import {
  buildGitignore,
  buildKnipConfig,
  buildJscpdConfig,
  validateTemplateFeatures,
} from '../src/features.js';
import { getTemplatesWithManifests } from '../src/index.js';

process.env.SKELETOR_CLI_TEST = '1';

describe('features registry', () => {
  test('buildGitignore merges feature fragments', () => {
    const out = buildGitignore(['node', 'jest', 'jscpd']);
    expect(out).toContain('node_modules/');
    expect(out).toContain('coverage/');
    expect(out).toContain('.jscpd/');
    expect(out).toContain('Generated by skeletor from template features');
  });

  test('buildGitignore keeps .env.example trackable after the .env.* rule', () => {
    const lines = buildGitignore(['python']).split('\n');
    expect(lines.indexOf('.env.*')).toBeGreaterThan(-1);
    expect(lines.indexOf('!.env.example')).toBeGreaterThan(lines.indexOf('.env.*'));
  });

  test('buildGitignore fills tokens from vars', () => {
    expect(buildGitignore(['go'], { PROJECT_NAME: 'my-app' }).split('\n')).toEqual(expect.arrayContaining(['/my-app', 'bin/']));
  });

  test('buildKnipConfig respects language', () => {
    const js = buildKnipConfig(['knip'], { language: 'javascript' });
    const ts = buildKnipConfig(['knip'], { language: 'typescript' });
    expect(js.entry[0]).toContain('.js');
    expect(ts.entry[0]).toContain('.ts');
  });

  test('buildJscpdConfig respects language', () => {
    const ts = buildJscpdConfig(['jscpd'], { language: 'typescript' });
    expect(ts.formatsExts.typescript).toEqual(['ts', 'tsx']);
  });

  test('all templates with features pass validation', () => {
    const templates = getTemplatesWithManifests();
    const errors = templates.flatMap((t) => validateTemplateFeatures(t));
    expect(errors).toEqual([]);
  });

  // ESLint does not read .gitignore, so every output directory it lists must be in the eslint ignores too.
  test.each(['javascript', 'typescript'])('%s eslint.config.js ignores the generated-output directories', (id) => {
    const tmpl = getTemplatesWithManifests().find((t) => t.id === id);
    const notOutput = new Set(['node_modules/', '.idea/', '.vscode/', 'logs/']);
    const outputDirs = buildGitignore(tmpl.features)
      .split('\n')
      .filter((line) => line.endsWith('/') && !notOutput.has(line));
    const eslintConfig = fs.readFileSync(path.join('templates', id, 'eslint.config.js'), 'utf8');
    expect(outputDirs).toEqual(expect.arrayContaining(['dist/', 'coverage/', 'report/', 'reports/', '.jscpd/']));
    for (const dir of outputDirs) {
      expect({ dir, ignored: eslintConfig.includes(`'${dir}**'`) }).toEqual({ dir, ignored: true });
    }
  });
});
