import fs from 'fs';
import path from 'path';

/**
 * Feature → config fragment registry for manifest-driven .gitignore and tool configs.
 * Templates with a `features` array in template.json get generated configs; others keep static files.
 */

const BASE_GITIGNORE = [
  '# Generated by skeletor from template features',
  '',
  '# OS / editor',
  '.DS_Store',
  'Thumbs.db',
  '.idea/',
  '.vscode/',
  '*.swp',
];

export const FEATURE_REGISTRY = {
  node: {
    gitignore: [
      '# Dependencies',
      'node_modules/',
      '',
      '# Build / output',
      'dist/',
      'build/',
      '',
      '# Env & secrets',
      '.env',
      '.env.*',
      '*.local',
      '',
      '# Logs',
      '*.log',
      'logs/',
    ],
  },
  jest: {
    gitignore: ['coverage/', 'report/', 'reports/'],
  },
  prettier: { gitignore: [] },
  eslint: { gitignore: [] },
  husky: { gitignore: [] },
  knip: { gitignore: [] },
  jscpd: { gitignore: ['report/', 'reports/', '.jscpd/'] },
  madge: { gitignore: [] },
  'prompt-gen': { gitignore: ['prompt.md'] },
  python: {
    gitignore: [
      '__pycache__/',
      '*.py[cod]',
      '.pytest_cache/',
      '.mypy_cache/',
      '.ruff_cache/',
      '.venv/',
      'venv/',
      'dist/',
      '*.egg-info/',
      '.coverage',
      'htmlcov/',
    ],
  },
  'python-uv': { gitignore: [] },
  go: { gitignore: ['bin/', 'vendor/'] },
  rust: { gitignore: ['/target/'] },
  java: { gitignore: ['target/'] },
  dotnet: { gitignore: ['bin/', 'obj/'] },
};

/** Ordered rules: first match wins (avoids false positives like "cargo test" matching "go test"). */
export const VERIFY_COMMAND_RULES = [
  { test: (cmd) => cmd.startsWith('npm install'), features: ['node'] },
  { test: (cmd) => cmd.includes('npm run format'), features: ['prettier'] },
  { test: (cmd) => cmd.includes('npm run lint'), features: ['eslint'] },
  { test: (cmd) => cmd.startsWith('npm test'), features: ['jest'] },
  { test: (cmd) => cmd.includes('npm run build'), features: ['node'] },
  { test: (cmd) => cmd.includes('npm run health:full'), features: ['knip', 'jscpd', 'madge'] },
  { test: (cmd) => cmd.includes('python -m pip'), features: ['python'] },
  { test: (cmd) => cmd.startsWith('uv sync'), features: ['python', 'python-uv'] },
  { test: (cmd) => cmd.includes('ruff'), features: ['python'] },
  { test: (cmd) => cmd.includes('pytest'), features: ['python'] },
  { test: (cmd) => cmd.includes('mypy'), features: ['python'] },
  { test: (cmd) => cmd.startsWith('go mod'), features: ['go'] },
  { test: (cmd) => cmd.startsWith('go build'), features: ['go'] },
  { test: (cmd) => cmd.startsWith('go test'), features: ['go'] },
  { test: (cmd) => cmd.startsWith('cargo fmt'), features: ['rust'] },
  { test: (cmd) => cmd.startsWith('cargo clippy'), features: ['rust'] },
  { test: (cmd) => cmd.startsWith('cargo check'), features: ['rust'] },
  { test: (cmd) => cmd.startsWith('cargo test'), features: ['rust'] },
  { test: (cmd) => cmd.startsWith('mvn'), features: ['java'] },
  { test: (cmd) => cmd.startsWith('dotnet'), features: ['dotnet'] },
];

/**
 * @param {string[]} features
 * @returns {string}
 */
export function buildGitignore(features) {
  const lines = [...BASE_GITIGNORE];
  const seen = new Set(lines);
  for (const feature of features) {
    const fragment = FEATURE_REGISTRY[feature]?.gitignore || [];
    for (const line of fragment) {
      if (!seen.has(line)) {
        seen.add(line);
        lines.push(line);
      }
    }
  }
  return `${lines.join('\n')}\n`;
}

/**
 * @param {string[]} features
 * @param {{ language?: string }} templateInfo
 */
export function buildKnipConfig(features, templateInfo) {
  if (!features.includes('knip')) return null;
  const isTs = templateInfo.language === 'typescript';
  const ext = isTs ? 'ts' : 'js';
  return {
    $schema: 'https://unpkg.com/knip@5/schema.json',
    entry: [`src/index.${ext}`],
    project: [`src/**/*.${ext}`, `tests/**/*.${ext}`],
    ignore: ['db/**', 'migrations/**', 'scripts/**'],
    ignoreExportsUsedInFile: true,
  };
}

/**
 * @param {string[]} features
 * @param {{ language?: string }} templateInfo
 */
export function buildJscpdConfig(features, templateInfo) {
  if (!features.includes('jscpd')) return null;
  const isTs = templateInfo.language === 'typescript';
  const testGlob = isTs ? '**/*.test.ts' : '**/*.test.js';
  const specGlob = isTs ? '**/*.spec.ts' : '**/*.spec.js';
  const langKey = isTs ? 'typescript' : 'javascript';
  const exts = isTs ? ['ts', 'tsx'] : ['js', 'jsx'];
  return {
    threshold: 5,
    reporters: ['html', 'console'],
    ignore: ['**/node_modules/**', '**/dist/**', '**/build/**', specGlob, testGlob],
    absolute: true,
    gitignore: true,
    minLines: 5,
    minTokens: 50,
    formatsExts: { [langKey]: exts },
  };
}

/**
 * @param {{ features?: string[], verifyCommands?: string[], id?: string }} templateInfo
 * @returns {string[]}
 */
export function validateTemplateFeatures(templateInfo) {
  const errors = [];
  const features = templateInfo.features;
  if (!Array.isArray(features) || features.length === 0) return errors;

  for (const feature of features) {
    if (!FEATURE_REGISTRY[feature]) {
      errors.push(`Template "${templateInfo.id}": unknown feature "${feature}"`);
    }
  }

  for (const cmd of templateInfo.verifyCommands || []) {
    const rule = VERIFY_COMMAND_RULES.find((r) => r.test(cmd));
    if (!rule) continue;
    for (const feat of rule.features) {
      if (!features.includes(feat)) {
        errors.push(
          `Template "${templateInfo.id}": verifyCommand "${cmd}" requires feature "${feat}"`,
        );
      }
    }
  }

  return errors;
}

/**
 * Write manifest-driven config files into a generated project.
 * @param {string} targetDir
 * @param {{ features?: string[], language?: string }} templateInfo
 */
export function applyFeatureConfigs(targetDir, templateInfo) {
  const features = templateInfo.features;
  if (!Array.isArray(features) || features.length === 0) return;

  fs.writeFileSync(path.join(targetDir, '.gitignore'), buildGitignore(features), 'utf8');

  const knip = buildKnipConfig(features, templateInfo);
  if (knip) {
    fs.writeFileSync(path.join(targetDir, 'knip.json'), `${JSON.stringify(knip, null, 2)}\n`, 'utf8');
  }

  const jscpd = buildJscpdConfig(features, templateInfo);
  if (jscpd) {
    fs.writeFileSync(path.join(targetDir, '.jscpd.json'), `${JSON.stringify(jscpd, null, 2)}\n`, 'utf8');
  }
}